### ISSUE TITLE
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE.

### ISSUE THREAD

**Issue by KianSabzi** [hamidrezafarzin/Cloudflare-PyPI-Mirror-Worker#1]
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.

I got the error when i install new package with this command :

pip install --index-url https://my_worker_url_on_cloudflare/pypi/simple pandas

**Comment by hamidrezafarzin** [comment]
Hi @KianSabzi 
Thank you for bringing this issue to my attention. The error you encountered typically occurs when there's a mismatch between the package version and the hash specified in the requirements file.

To address this issue, please follow these steps:

1. Double-check the contents of your requirements file (requirements.txt) to ensure that the package name, version, and hash are accurate. You can use the pip freeze --hashes command to generate the correct hash for each package version.
2. Manually inspect the contents of the package on your Cloudflare PyPI mirror to ensure they match the original package from the official PyPI repository. You can download the package from the mirror and compare it with the original package.
3. Once you've verified the accuracy of the packages and their hashes, try installing the package again using the pip install command. If the issue persists, please provide me with more details so that i can assist you further.

All the packages are taken from the [ pythonhosted site ](https://files.pythonhosted.org) and no manipulation is done on them
I tested the command and it was installed without any problem

**Comment by AmirhosseinDehghanazar** [comment]
I have tired it out and it was completely ok ! l 
I have to say that, I used **"--no-cache-dir"**  attribute in **pip install** and it was working perfectly !

**Comment by hamidrezafarzin** [comment]
Since there hasn't been any activity on this issue for some time, I'm going to close it now to keep things organized. 

If you still need assistance with this or believe it's a valid concern, feel free to reopen it, and we can continue from there.

Thank you for your understanding.

Best regards,
Hamidreza Farzin.
